# Experience API - common config
current.app:
  name: "parking-experience-api"
  version: "0.0.1"

project:
  artifactId: "parking-experience-api"
  version: "0.0.1"

raml:
  api:
    location: "api/parking-experience-api.raml"

connector:
  retries: "3"
  retryInterval: "5000"
  response:
    timeout: "60000"

